### ISSUE TITLE
CardManager.search_card initializes TokenContext with identity=None, breaking all searches?

### ISSUE THREAD

**Issue by kevinseelbach** [VirgilSecurity/virgil-sdk-python#49]
https://github.com/VirgilSecurity/virgil-sdk-python/blob/139c341992b996cb1b2d2e0e55aed8b12c2073c9/virgil_sdk/cards/card_manager.py#L162

Having some issues doing a simple search for cards, I went to look at the SDK code and found what looks like a potential issue?

Test code to reproduce issue:
```
import datetime

from virgil_crypto import VirgilCrypto
from virgil_crypto.access_token_signer import AccessTokenSigner
from virgil_crypto.card_crypto import CardCrypto
from virgil_sdk import CardManager, VirgilCardVerifier
from virgil_sdk.jwt import JwtGenerator
from virgil_sdk.jwt.providers import CallbackJwtProvider
from virgil_sdk.utils import Utils

def generate_jwt(token_context, token_ttl) -> str:
    crypto_instance = VirgilCrypto()
    token_ttl = datetime.timedelta(hours=1).seconds
    imported_api_private_key = crypto_instance.import_private_key(Utils.b64decode(settings.VIRGIL_API_KEY))  # replace with your api key
    builder = JwtGenerator(
        settings.VIRGIL_APP_ID,  # replace
        imported_api_private_key, 
        settings.VIRGIL_API_KEY_ID,  # replace with your api key id
        token_ttl,
        AccessTokenSigner(crypto_instance)
    )
    identity = token_context.identity
    token = builder.generate_token(identity).to_string()
    return token


def get_token_from_server(token_context, ttl=20):
    return generate_jwt(token_context, ttl)

VIRGIL_CRYPTO = VirgilCrypto()
CARD_CRYPTO = CardCrypto(VIRGIL_CRYPTO)
CARD_VERIFIER = VirgilCardVerifier(CARD_CRYPTO)
CARD_MANAGER = CardManager(card_crypto=CARD_CRYPTO,
                           card_verifier=CARD_VERIFIER,
                           access_token_provider=CallbackJwtProvider(get_token_from_server))
cards = CARD_MANAGER.search_card('testuser6')  # replace with a known test user name

print(cards)
```

Without changing the relevant line in `card_manager.py`, this error is raised:

```
Traceback (most recent call last):
  File "/Users/kevinvseelbach/Library/Preferences/PyCharm2018.3/scratches/scratch_8.py", line 78, in <module>
    cards = CARD_MANAGER.search_card('testuser6')
  File "/.venv/lib/python3.7/site-packages/virgil_sdk/cards/card_manager.py", line 163, in search_card
    access_token = self._access_token_provider.get_token(token_context)
  File "/.venv/lib/python3.7/site-packages/virgil_sdk/jwt/providers/callback_jwt_provider.py", line 63, in get_token
    return Jwt.from_string(self.__get_token_callback(token_context))
  File "/Users/kevinvseelbach/Library/Preferences/PyCharm2018.3/scratches/scratch_8.py", line 70, in get_token_from_server
    return generate_jwt(token_context, ttl)
  File "/Users/kevinvseelbach/Library/Preferences/PyCharm2018.3/scratches/scratch_8.py", line 65, in generate_jwt
    token = builder.generate_token(identity).to_string()
  File "/.venv/lib/python3.7/site-packages/virgil_sdk/jwt/jwt_generator.py", line 91, in generate_token
    data
  File "/.venv/lib/python3.7/site-packages/virgil_sdk/jwt/jwt_body_content.py", line 62, in __init__
    self.subject = str(self.__IDENTITY_PREFIX + self._identity)
TypeError: can only concatenate str (not "NoneType") to str
```

By changing the relevant line in `CardManager.search_card` initialize `TokenContext` with the `identity` parameter, i.e.:

```
 def search_card(self, identity):
        # type: (Union[str, list]) -> List[Card]
        """
        Searches for cards by specified identity.

        Args:
            identity: The identity (or list of identity) to be found.

        Returns:
            The list of found Card.
        """
        if not identity:
            raise ValueError("Missing identity for search")
        token_context = TokenContext(identity, "search")
```

the result is as expected:

```
.venv/bin/python /Users/kevinvseelbach/Library/Preferences/PyCharm2018.3/scratches/scratch_8.py
testuser6
[<virgil_sdk.cards.card.Card object at 0x10e3b29e8>]

Process finished with exit code 0
```

It's hard to tell, but I think some of the test setup code in these methods is hiding this problem: https://github.com/VirgilSecurity/virgil-sdk-python/blob/139c341992b996cb1b2d2e0e55aed8b12c2073c9/virgil_sdk/tests/base_test.py#L108  
https://github.com/VirgilSecurity/virgil-sdk-python/blob/139c341992b996cb1b2d2e0e55aed8b12c2073c9/virgil_sdk/tests/base_test.py#L125

**Comment by kevinseelbach** [comment]
Looking a little further in `card_manager.py` , I see that `TokenContext` is initialized in several places like `TokenContext(None, "action")`, and the specific exception raised above is due to a `None + string` concat in `JwtBodyContent`. If I change the line in `JwtGenerator.generate_token` where it initializes `JwtBodyContent` to do it like this, this also seems to resolve my issue:

```
     jwt_body = JwtBodyContent(
            self._app_id,
            identity or "",  # this line changed pass empty string if identity is None
            issued_at,
            expires_at,
            data
        )
```

Maybe this is a more appropriate fix? Please inform if I am just using the SDK wrong..

**Comment by Imelstorm** [comment]
Thanks for the questions.
The Publish Card example is simplified because the person who owns the Card and the person who publishes the Card are the same. This example skips your service authentication part, that it is needed to get user identity (who will search the card) for jwt generation.

Please take a look at the [sample_backend_for_jwt_generation.py](https://github.com/VirgilSecurity/virgil-sdk-python/blob/master/examples/sample_backend_for_jwt_generation.py) to find out on how to set up your server side to get a JWT for the client who will search someone's Card 
```python
def generate_jwt(token_context, token_ttl) -> str:
    crypto_instance = VirgilCrypto()
    token_ttl = datetime.timedelta(hours=1).seconds
    imported_api_private_key = crypto_instance.import_private_key(Utils.b64decode(settings.VIRGIL_API_KEY))  # replace with your api key
    builder = JwtGenerator(
        settings.VIRGIL_APP_ID,  # replace
        imported_api_private_key,
        settings.VIRGIL_API_KEY_ID,  # replace with your api key id
        token_ttl,
        AccessTokenSigner(crypto_instance)
    )
    identity = your_service_identity # This field will contain the identity of existence card user of your service from who searches do.
    token = builder.generate_token(identity).to_string()
    return token
```

If there are any other questions you also can ask us in our Slack Community
https://virgilsecurity.com/join-community

**Comment by kevinseelbach** [comment]
@Imelstorm 
I posted a message in #technicalsupport on slack. Copied below... 

I was able to get it working (searching for cards), but only by subclassing JwtGenerator and fixing the line that allows `identity` to be `None`. I'm not sure if the Python SDK is used as extensively as the Node.js SDKs, or if I am doing something wrong. From what I can see, it looks like there are several paths where `JwtGenerator.generate_token` may be called with a `None` argument for `identity`, since it is called indirectly by `CardManager` in several places with a `TokenContext(identity=None, operation="search|get|...")`. What happens as a result, is that `JwtGenerator.generate_token` attempts to instantiate a `JwtBodyContent` object (virgil_sdk/jwt/jwt_generator.py:86), and at the bottom of the `__init__` method for that class, it fails to concatenate `None` + the default `str` for `self.__IDENTITY_PREFIX`. I coded around it for now, but I don't understand what I'm missing, if anything, or if I'm just the first person who's running into this. I'm on Python 3.7.2.

**Comment by Imelstorm** [comment]
Hi @kevinseelbach, 
I've made some example of how to use card search [search_card_on_client_side.py](https://github.com/VirgilSecurity/virgil-sdk-python/blob/master/examples/search_card_on_client_side.py) and changed a confusing part of card publishing [publish_card_from_client_side.py](https://github.com/VirgilSecurity/virgil-sdk-python/blob/master/examples/publish_card_from_client_side.py)

**Comment by kevinseelbach** [comment]
I will need to verify this tomorrow, but having read through your updated search example, it appears to be doing exactly what I have done in both my examples and (private) product code, and I am wondering if you guys are ignoring my comments about the TypeError that can be raised when search card is called? I haven’t run this code yet, but it looks like it is going to raise the exact same error due to previously mentioned reasons.

**Comment by acenario** [comment]
Noticed this is still an issue? This line of code is incorrect:

`token_context = TokenContext(None, "search")`

**Comment by acenario** [comment]
I subclassed the file for CardManager and fixed the line. I assume I'll need to do the same as errors occur.
